[SDK-2597] UPGRADE.md updates for 8.x changes
auth0/auth0-PHP pull request #510
Opened 2021-06-07 14:38 UTC by evansims

This PR includes work toward updating the UPGRADE.md file (previously `MIGRATE-v5-TO-v7.md`) to guide developers through upgrading their apps to 8.x, pointing out breaking changes and pitfalls and giving examples of using the new features to streamline their apps.

This is a work in progress.

2021-06-15 18:52 UTC, evansims commented on src/Auth0.php
> +    /**
Unrelated to this PR, but this suggestion came through via the community forums and I thought it was a good one, so I'm sneaking it in here.

2021-06-16 09:01 UTC, stevehobbsdev requested changes
Hey @evansims, nice work here, you've obviously put a lot into it. I just left some mostly minor stuff for you.

I've had a read through the upgrade doc and the overriding feeling I have about it is that there isn't really one list or round up of the things that would actually break me if I was to uprgade to the latest version. Generally, it's there, but I really have to dig into the detail to figure out if I'm affected or not, amongst wording like "You can now use the.." and "SDK v8.0 offers a cleaner approach". What I was expecting to see is a heading that is literally "BREAKING CHANGES" (although not necessarily in caps 😄 ) and then a bullet-list of what I should be concerned about as a developer. Then all the awesome detail about the changes can come after. Is that possible here?

Otherwise, nice work 👍🏻

2021-06-18 00:46 UTC, evansims commented on README.md
> -<a href="https://packagist.org/packages/auth0/auth0-PHP"><img src="https://img.shields.io/packagist/php-v/auth0/auth0-php" alt="PHP Support"></a>
That's fair, I'll re-add some of these

2021-06-18 00:47 UTC, evansims commented on README.md
> +- A PSR-16 caching library is strongly recommended for performance reasons. (↗ [Find libraries](https://packagist.org/search/?query=PSR-16&type=library&tags=psr%2016))
Good call, I'll link these references to them as well

2021-06-18 01:03 UTC, evansims commented
Hey @stevehobbsdev, thanks for the awesome feedback! I've tried to incorporate everything you suggested now. I've surfaced the more potentially breaking changes (depending on how the developer may be using the SDK, of course) in the UGPRADE.md file. See what you think of this approach 🤔

2021-06-20 06:04 UTC, Nyholm reviewed
There could be a good idea to keep all the old upgrade documents. 
Ie, Upgrade-5-to-7.md and Upgrade-7-to-8.md.

2021-06-20 06:04 UTC, Nyholm commented on README.md
> +| Option Name           | Allowed Types                     | Required | Default                          | Description
This table is appreciated. Thank you

2021-06-21 05:31 UTC, merged